artifacts:
  ARTIFACTS_DIR: artifacts
  NER_MODEL_DIR: artifacts/ner_model
  BLESSED_MODEL_FILE_PATH: artifacts/ner_model/pytorch_model.bin
  BLESSED_MODEL_CONFIG_FILE_PATH: artifacts/ner_model/config.json

logs:
  LOGS_DIR : logs
  RUNNING_LOGS_FILE_PATH: logs/running_logs.log

s3_config:
  BUCKET_NAME: nlp-hub
  REGION: us-east-2
  BLESSED_MODEL_FILE_PATH: artifacts/ner_model/pytorch_model.bin
  BLESSED_MODEL_CONFIG_FILE_PATH: artifacts/ner_model/config.json

  LOGS_FILE_PATH : logs/running_logs.log

model_serving:
  NER_PRODUCTION_MODEL_PATH: src/production_models/ner_model
  SOUND_SPEECH_TO_TEXT_FILE_PATH: src/sounds/speech_to_text.wav
  SOUND_TEXT_TO_SPEECH_FILE_PATH: src/sounds/converted-file.mp3
  
  APP_HOST : 0.0.0.0
  APP_PORT : 8080
  API_TITLE: NLP-Hub
  API_DESCRIPTION: NLP-Hub provides production-grade REST API service for widely used NLP applications
  API_VERSION: 0.0.1
